// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfG8ioxp62bI6QpjKVUwUj-PU9Fv_JyB8',
    appId: '1:472170550229:web:cbac1cb167a0dcecefa35c',
    messagingSenderId: '472170550229',
    projectId: 'pushnotification-8ccb4',
    authDomain: 'pushnotification-8ccb4.firebaseapp.com',
    storageBucket: 'pushnotification-8ccb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxVcf8d7mtz-r_Su_GlSA_oaThPpzH_jg',
    appId: '1:472170550229:android:e85820f2cbe54d7cefa35c',
    messagingSenderId: '472170550229',
    projectId: 'pushnotification-8ccb4',
    storageBucket: 'pushnotification-8ccb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzOx8YDh-RHdUHrqT3V_RJn2oYWolFwQ',
    appId: '1:472170550229:ios:ae3ee13f59856babefa35c',
    messagingSenderId: '472170550229',
    projectId: 'pushnotification-8ccb4',
    storageBucket: 'pushnotification-8ccb4.appspot.com',
    iosClientId: '472170550229-1624q7o30b4mkg21vdqndr97gbqgcdcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNzOx8YDh-RHdUHrqT3V_RJn2oYWolFwQ',
    appId: '1:472170550229:ios:59b5226e6c5f18c3efa35c',
    messagingSenderId: '472170550229',
    projectId: 'pushnotification-8ccb4',
    storageBucket: 'pushnotification-8ccb4.appspot.com',
    iosClientId: '472170550229-it20utpqod9d9cv270k1bah7sdihcr5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
